// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolarHomeAuto.Infrastructure.DataStore.SqlServer;

#nullable disable

namespace SolarHomeAuto.Infrastructure.DataStore.SqlServer.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20230804164528_RemoveTables")]
    partial class RemoveTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolarHomeAuto.Infrastructure.DataStore.Entities.ApplicationStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsBackgroundServiceRunning")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ApplicationState", (string)null);
                });

            modelBuilder.Entity("SolarHomeAuto.Infrastructure.DataStore.Entities.AuthTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("AuthToken", (string)null);
                });

            modelBuilder.Entity("SolarHomeAuto.Infrastructure.DataStore.Entities.DeviceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Provider")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProviderData")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("SolarJobs")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("StateType")
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DeviceId" }, "IX_Device_DeviceId")
                        .IsUnique()
                        .HasFilter("[DeviceId] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex(new[] { "DeviceId" }, "IX_Device_DeviceId"), false);

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("SolarHomeAuto.Infrastructure.DataStore.Entities.DeviceHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Error")
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsStateChange")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("State")
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Date" }, "IX_DeviceHistory_Date");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex(new[] { "Date" }, "IX_DeviceHistory_Date"), false);

                    b.HasIndex(new[] { "DeviceId" }, "IX_DeviceHistory_DeviceId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex(new[] { "DeviceId" }, "IX_DeviceHistory_DeviceId"), false);

                    b.ToTable("DeviceHistory", (string)null);
                });

            modelBuilder.Entity("SolarHomeAuto.Infrastructure.DataStore.Entities.LogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Logger")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("Log", (string)null);
                });

            modelBuilder.Entity("SolarHomeAuto.Infrastructure.DataStore.Entities.SolarRealTimeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BatteryCapacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("BatteryCharging")
                        .HasColumnType("bit");

                    b.Property<decimal?>("BatteryPower")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Consumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GridPower")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("GridPurchasing")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Production")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Date" }, "IX_SolarRealTime_Date");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex(new[] { "Date" }, "IX_SolarRealTime_Date"), false);

                    b.ToTable("SolarRealTime", (string)null);
                });

            modelBuilder.Entity("SolarHomeAuto.Infrastructure.DataStore.Entities.SolarStatsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChargeCapacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Consumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DischargeCapacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Generation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GridFeedIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GridPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Date" }, "IX_SolarStats_Date");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex(new[] { "Date" }, "IX_SolarStats_Date"), false);

                    b.ToTable("SolarStats", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
